### ISSUE TITLE
Regarding Hololens Image Based Texture Repo

### ISSUE THREAD

**Issue by lordlycastle** [weijia-yu/notes#1]
Hi @weijia-yu ,

I apologize for using this issue as a message but GitHub doesn't provide a way for me to get a message to you. I'll keep this short.

I'm contacting regarding the https://github.com/weijia-yu/Hololens_Image_Based_Texture/ which was taken down due to DMCA claims. I'm very interested in seeing the project source as it seems relevant to my research. So would you be willing to share the project code excluding the Easy Save package which was the reason for the take down? 

I would appreciate that very much.

Please feel free to tell me if you wish to discuss this privately and I'll provide an email.

Thanks a bunch!

**Comment by astaikos316** [comment]
@weijia-yu i am also very interested in the Hololens_Image_Based_Texture repository as it is extremely relevant to my research.  If there is a way to share the code it would be greatly appreciated.

**Comment by EpicMax88** [comment]
@weijia-yu  This is something where i have been looking for, would you be able to share it?  Thnx in advance
